# Generated by Django 5.0.1 on 2024-01-07 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitools', '0004_tool_tags_alter_tool_category_alter_tool_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='rating',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
